# Generated by Django 4.1.7 on 2023-02-28 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accredetation_app', '0001_initial'),
        ('trainer_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Excel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_No', models.CharField(max_length=20)),
                ('Name_Of_Delegates', models.CharField(max_length=100)),
                ('Certificate_No', models.CharField(max_length=40)),
                ('Course', models.CharField(max_length=40)),
                ('Company', models.CharField(max_length=50)),
                ('Date_Of_issue', models.DateField()),
                ('Date_Of_Expiry', models.DateField()),
                ('Instructor', models.CharField(max_length=40)),
                ('pdf_url', models.TextField(blank=True, null=True)),
                ('accreditaion_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excel_expiry', to='accredetation_app.accriditaion')),
                ('instructor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excel_instructor', to='trainer_app.trainer')),
            ],
            options={
                'db_table': 'Excel',
            },
        ),
    ]
