# Generated by Django 4.1.7 on 2023-02-28 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accriditaion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_accreditation', models.CharField(max_length=100)),
                ('expiry_date', models.DateField()),
                ('accreditation_logo', models.FileField(unique=True, upload_to='shop')),
            ],
            options={
                'db_table': 'Accriditation',
            },
        ),
    ]
